name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [29]
        target: [default]
        abi: [x86]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # hoặc 'adopt' nếu cần thiết
        java-version: 11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: "latest"
        accept-android-sdk-licenses: true

    - name: Build with Gradle
      run: ./gradlew build
