name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [29]
        target: [default]
        abi: [x86]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 29
        target: default
        arch: x86
        ndk-version: '22.1.7171670'

    - name: Build with Gradle
      run: ./gradlew build
